#!/bin/bash
# shellcheck disable=SC1091,SC2154

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

if [[ "$new_path" != "/" ]]; then
	ynh_die --message="QuestarrNG does not support URL subpaths. Choose the root of a dedicated domain."
fi

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping QuestarrNG..."
ynh_systemctl --service="$app" --action="stop"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating QuestarrNG's Nginx and application URL configuration..."
ynh_config_change_url_nginx
ynh_config_add_systemd
questarrng_register_service

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting QuestarrNG..."
questarrng_start_service

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Change of URL completed for $app"
