#!/bin/bash
# shellcheck disable=SC1091,SC2154

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing the YunoHost service and reverse proxy..."
if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
	yunohost service remove "$app"
fi
ynh_config_remove_systemd
ynh_config_remove_nginx
ynh_config_remove_logrotate

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Removal of $app completed"
