#!/bin/bash
# shellcheck disable=SC1091,SC2154

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping QuestarrNG..."
ynh_systemctl --service="$app" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading QuestarrNG source files..."
ynh_setup_source --dest_dir="$install_dir" --full_replace

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
questarrng_prepare_data
questarrng_build_app
questarrng_install_apprise
questarrng_prepare_service
questarrng_register_service

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting QuestarrNG..."
questarrng_start_service

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Upgrade of $app completed"
