import { randomUUID } from "crypto";
import { count, eq, sql } from "drizzle-orm";
import type { NodePgDatabase } from "drizzle-orm/node-postgres";
import { db as appDb } from "../db.js";
import * as pgSchema from "../../shared/schema.pg.js";
import { encryptCredentialSync } from "../credential-crypto.js";
import {
  validateIndexerInput,
  buildIndexerUpdate,
  buildNewIndexer,
  formatSyncFailure,
} from "./transactional-ops.shared.js";
import type {
  ApiKeyPublic,
  Game,
  Indexer,
  InsertPlatformMapping,
  InsertUser,
  User,
} from "../../shared/schema.js";
import type { SyncIndexersResult } from "./transactional-ops.js";

/**
 * Postgres implementations.
 *
 * node-postgres transactions are async: the callback returns a promise and
 * statements are awaited rather than finished with .all()/.run(). Behaviour is
 * intended to match ./transactional-ops.sqlite.ts exactly; only the execution
 * model differs. See ./transactional-ops.ts for why they cannot be one body.
 *
 * This module is only ever loaded with Postgres active, so it can use the
 * Postgres tables and their real types directly instead of the app-wide
 * SQLite-shaped view of the schema.
 */
const { apiKeys, games, indexers, platformMappings, systemConfig, users } = pgSchema;
const db = appDb as unknown as NodePgDatabase<typeof pgSchema>;

export async function seedPlatformMappingsIfEmpty(
  mappings: InsertPlatformMapping[]
): Promise<{ seeded: boolean; count: number }> {
  return db.transaction(async (tx) => {
    // A bare count() aggregate with no GROUP BY always returns exactly one
    // row, even over an empty table, so these destructures can't come up
    // short -- the `!` documents that guarantee rather than working around it.
    const [existing] = await tx.select({ count: count() }).from(platformMappings);
    if (existing!.count > 0) {
      return { seeded: false, count: existing!.count };
    }

    for (const mapping of mappings) {
      await tx.insert(platformMappings).values({ ...mapping, id: randomUUID() });
    }

    const [seeded] = await tx.select({ count: count() }).from(platformMappings);
    return { seeded: true, count: seeded!.count };
  });
}

export async function registerSetupUser(insertUser: InsertUser): Promise<User> {
  return db.transaction(async (tx) => {
    // Postgres' default READ COMMITTED isolation lets two concurrent setup
    // requests both see zero users and both insert -- unlike better-sqlite3's
    // synchronous transactions, which serialize this for free. An exclusive
    // table lock forces the second transaction to wait for the first to
    // commit (or roll back) before it can even run its own count query.
    await tx.execute(sql`LOCK TABLE ${users} IN EXCLUSIVE MODE`);

    const [result] = await tx.select({ count: count() }).from(users);

    if (result!.count > 0) {
      throw new Error("Setup already completed");
    }

    // Ids are generated by the application on both dialects.
    const id = randomUUID();
    // A single-row insert's .returning() always yields exactly one row.
    const [user] = await tx
      .insert(users)
      .values({ ...insertUser, id, steamId64: null })
      .returning();
    return user!;
  });
}

export async function updateGamesBatch(
  updates: { id: string; data: Partial<Game> }[]
): Promise<void> {
  await db.transaction(async (tx) => {
    for (const update of updates) {
      await tx.update(games).set(update.data).where(eq(games.id, update.id));
    }
  });
}

export async function setSystemConfigBatch(
  entries: { key: string; value: string }[]
): Promise<void> {
  await db.transaction(async (tx) => {
    for (const { key, value } of entries) {
      await tx
        .insert(systemConfig)
        .values({ key, value })
        .onConflictDoUpdate({
          target: systemConfig.key,
          set: { value, updatedAt: new Date() },
        });
    }
  });
}

export async function syncIndexers(
  indexersToSync: Partial<Indexer>[],
  encryptionKey: Buffer
): Promise<SyncIndexersResult> {
  const results: SyncIndexersResult = {
    added: 0,
    updated: 0,
    failed: 0,
    errors: [],
  };

  await db.transaction(async (tx) => {
    // Fetch all existing indexers within the transaction to compare against
    const existingIndexers = await tx.select().from(indexers);
    const existingMap = new Map(existingIndexers.map((i) => [i.url, i]));

    for (const idx of indexersToSync) {
      try {
        const invalid = validateIndexerInput(idx);
        if (invalid) {
          results.failed++;
          results.errors.push(invalid);
          continue;
        }

        const existing = existingMap.get(idx.url as string);
        const encryptedApiKey = encryptCredentialSync(idx.apiKey as string, encryptionKey);

        // A failed statement aborts the whole Postgres transaction until
        // rollback, unlike SQLite. Each item runs in its own savepoint so one
        // bad indexer can't discard every item already processed in this batch.
        await tx.transaction(async (savepoint) => {
          if (existing) {
            await savepoint
              .update(indexers)
              .set(buildIndexerUpdate(idx, encryptedApiKey))
              .where(eq(indexers.id, existing.id));
          } else {
            await savepoint
              .insert(indexers)
              .values(buildNewIndexer(idx, encryptedApiKey, randomUUID()));
          }
        });

        if (existing) {
          results.updated++;
        } else {
          results.added++;
        }
      } catch (error) {
        results.failed++;
        results.errors.push(formatSyncFailure(idx, error));
      }
    }
  });

  return results;
}

export async function addApiKey(
  key: { userId: string; name: string; keyHash: string; prefix: string },
  maxKeys: number
): Promise<ApiKeyPublic> {
  // Counting and inserting inside one transaction is not enough on its own:
  // Postgres' default READ COMMITTED isolation lets two concurrent calls for
  // the same user both read the same under-limit count before either insert
  // lands. Locking the user's row first serializes concurrent callers so the
  // second one re-reads a count that already includes the first's insert.
  return db.transaction(async (tx) => {
    await tx.select().from(users).where(eq(users.id, key.userId)).for("update");

    const [keyCountRow] = await tx
      .select({ count: count() })
      .from(apiKeys)
      .where(eq(apiKeys.userId, key.userId));
    const existingKeys = keyCountRow!.count;

    if (existingKeys >= maxKeys) {
      throw new Error("API key limit reached");
    }

    // A single-row insert's .returning() always yields exactly one row.
    const [created] = await tx
      .insert(apiKeys)
      .values({ ...key, id: randomUUID() })
      .returning({
        id: apiKeys.id,
        userId: apiKeys.userId,
        name: apiKeys.name,
        prefix: apiKeys.prefix,
        createdAt: apiKeys.createdAt,
        lastUsedAt: apiKeys.lastUsedAt,
      });
    return created!;
  });
}
